### ISSUE TITLE
Slack Invitations

### ISSUE THREAD

**Issue by mintymac** [slashdotdash/awesome-elixir-cqrs#2]
Im very interested in joing the slack channel but I think we need a way to request an invite.  Love the README btw.  Thank you

**Comment by slashdotdash** [comment]
@mintymac You can get an invite to the Slack teams from the following places:

- Elixir slack team at https://elixir-slackin.herokuapp.com/
- ddd-cqrs-es at https://ddd-cqrs-es.herokuapp.com/

I'll add those links to the README. Thanks for the feedback.
